### ISSUE TITLE
[BUG] Missing indexing workflow monitoring link returned in CLI

### ISSUE THREAD

**Issue by julianpitt** [aws-samples/aws-genai-conversational-rag-reference#113]
### Describe the bug

When running through the document upload command, the Indexing workflow is started and mentions "To monitor, click this link" 
There is no link displayed.

### Expected Behavior

A link to be displayed allowing a user to to click on it and be brought to the Indexing workflow in the AWS Console.

### Current Behavior

No link is returned

### Reproduction Steps

After a successful deployement, open a termina and run the following
```
curl -O https://ws-assets-prod-iad-r-pdx-f3b3f9f1a7d6a3d0.s3.us-west-2.amazonaws.com/26a73587-1d61-401e-82f5-68b10ea84e48/sample-data.zip
unzip sample-data.zip
pnpm run galileo-cli document upload --metadataFile=./sample-data/metadata.json
```

Accept all the default options for your galileo deployement

![Screenshot 2024-03-12 at 6 30 42 pm](https://github.com/aws-samples/aws-genai-conversational-rag-reference/assets/8890146/f235d22a-79e1-43d0-8c1d-b1d3e767934d)

### Environment details (OS name and version, etc.)

Galileo Prerequisite Check...  system: Linux 6.5.0-1014-aws #14~22.04.1-Ubuntu SMP Thu Feb 15 15:27:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux pnpm: 8.15.4  node: v20.11.1  python: Python 3.11.0rc1  poetry: Poetry (version 1.8.2)  docker: Docker version 25.0.4, build 1a576c5  java: openjdk 18.0.2 2022-07-19 OpenJDK Runtime Environment Corretto-18.0.2.9.1 (build 18.0.2+9-FR) OpenJDK 64-Bit Server VM Corretto-18.0.2.9.1 (build 18.0.2+9-FR, mixed mode, sharing)  aws: aws-cli/2.15.28 Python/3.11.8 Linux/6.5.0-1014-aws exe/x86_64.ubuntu.22 prompt/off   Prerequisite check passed

**Comment by sperka** [comment]
This has only been tested with modern terminals.

The link is there and the terminal (should) highlight "click this" -- https://github.com/aws-samples/aws-genai-conversational-rag-reference/blob/6cc3706d2a0075d334022217a4a45e9994102ede/packages/galileo-cli/src/commands/document/upload/index.ts#L139

Will add the link as simple text.
