### ISSUE TITLE
deployment automation

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-conversational-rag-reference#118]
### Describe the feature

Dear all,

Could you pls. automate the deployment for Cloud9 as it was done in https://aws-samples.github.io/aws-genai-llm-chatbot/guide/deploy.html
It takes some time to get all prerequisites in place.

best regards
Alexey Shishkin

### Use Case

to speed up the installation and testing instead of checking the prerequisites

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by alexeyshishkin01** [comment]
I have tested the following commands for deployment:

wget -q -O - https://apt.corretto.aws/corretto.key | sudo gpg --dearmor -o /usr/share/keyrings/corretto-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main" | sudo tee /etc/apt/sources.list.d/corretto.list
sudo apt -qq update
sudo apt -qq install -y java-18-amazon-corretto-jdk

nvm install lts/iron
nvm use lts/iron
npm i -g pnpm

sudo apt -qq install -y python3.11
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 110
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 100
sudo update-alternatives --set python3 /usr/bin/python3.11
curl -sSL https://install.python-poetry.org | python3 -

pnpm install

They can be used in the script since they don't require user's response.

**Comment by martenpayne** [comment]
Cloud9 recommendations will be shortly replaced by devcontainer integration (work-in-progress)
