### ISSUE TITLE
The field "pnpm" was found

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-conversational-rag-reference#120]
### Describe the bug

in cloud9 I have the following warning message

cloud9:~/environment/aws-genai-conversational-rag-reference (mainline) $ pnpm install
.../generated/infrastructure/typescript  |  WARN  The field "pnpm" was found in /home/ubuntu/environment/aws-genai-conversational-rag-reference/demo/api/generated/infrastructure/typescript/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
.../typescript-react-query-hooks         |  WARN  The field "pnpm" was found in /home/ubuntu/environment/aws-genai-conversational-rag-reference/demo/api/generated/libraries/typescript-react-query-hooks/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
demo/api/generated/runtime/typescript    |  WARN  The field "pnpm" was found in /home/ubuntu/environment/aws-genai-conversational-rag-reference/demo/api/generated/runtime/typescript/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
demo/api/interceptors/typescript         |  WARN  The field "pnpm" was found in /home/ubuntu/environment/aws-genai-conversational-rag-reference/demo/api/interceptors/typescript/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
demo/corpus/logic                        |  WARN  The field "pnpm" was found in /home/ubuntu/environment/aws-genai-conversational-rag-reference/demo/corpus/logic/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
 WARN  6 other warnings

### Expected Behavior

no such warnings

### Current Behavior

cloud9:~/environment/aws-genai-conversational-rag-reference (mainline) $ pnpm install
.../generated/infrastructure/typescript  |  WARN  The field "pnpm" was found in /home/ubuntu/environment/aws-genai-conversational-rag-reference/demo/api/generated/infrastructure/typescript/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
.../typescript-react-query-hooks         |  WARN  The field "pnpm" was found in /home/ubuntu/environment/aws-genai-conversational-rag-reference/demo/api/generated/libraries/typescript-react-query-hooks/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
demo/api/generated/runtime/typescript    |  WARN  The field "pnpm" was found in /home/ubuntu/environment/aws-genai-conversational-rag-reference/demo/api/generated/runtime/typescript/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
demo/api/interceptors/typescript         |  WARN  The field "pnpm" was found in /home/ubuntu/environment/aws-genai-conversational-rag-reference/demo/api/interceptors/typescript/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
demo/corpus/logic                        |  WARN  The field "pnpm" was found in /home/ubuntu/environment/aws-genai-conversational-rag-reference/demo/corpus/logic/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
 WARN  6 other warnings

### Reproduction Steps

pnpm install

### Environment details (OS name and version, etc.)

cloud9:~/environment $ pnpm run prerequisite-check  ERR_PNPM_NO_SCRIPT  Missing script: prerequisite-check  Command "prerequisite-check" not found.

**Comment by martenpayne** [comment]
Thanks for creating this issue. The documentation (in particular the prerequisites) and code have been updated, and when I follow install instructions in a new cloud9 environment, no warnings are generated.
