### ISSUE TITLE
to add resize script to change the size of Cloud9 EBS volume

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-conversational-rag-reference#121]
### Describe the feature

the documentation requires to increase the size of Cloud9 EBS volume - https://aws-samples.github.io/aws-genai-conversational-rag-reference/overview/quick-start/
a ready-to-use script can be useful

### Use Case

Pls. have a look at https://github.com/aws-samples/aws-genai-llm-chatbot/issues/446

### Proposed Solution

Pls. have a look at https://github.com/aws-samples/aws-genai-llm-chatbot/issues/446

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by martenpayne** [comment]
addressed in updated documentation
