### ISSUE TITLE
deployment guide is to be improved

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-conversational-rag-reference#123]
### Describe the issue

pls. improved the deployment guide, so that it's clear what to do and there're copy-paste commands for deployment
as an example pls. refer to the following links:
https://aws-samples.github.io/aws-genai-llm-chatbot/guide/deploy.html
https://aws-samples.github.io/aws-genai-llm-chatbot/guide/deploy.html#aws-cloud9
https://aws-samples.github.io/aws-genai-llm-chatbot/guide/deploy.html#deployment

### Links

what I have currently is:
- the first page - https://github.com/aws-samples/aws-genai-conversational-rag-reference
- which refers to the full documentation link - https://aws-samples.github.io/aws-genai-conversational-rag-reference/overview/
- the full documentation page has the 'Getting Started' chapter - https://aws-samples.github.io/aws-genai-conversational-rag-reference/overview/quick-start/
- 'Getting Started' chapter is poorly structured and and it takes time to understand how to deploy the proposed solution

**Comment by martenpayne** [comment]
Documentation improvements now work-in-progress

**Comment by martenpayne** [comment]
Please let me know what you think of the restructured documentation - adding clipboard affordances is will a WIP
