### ISSUE TITLE
(node:6235) [EACCES] Error: spawn galileo-cli EACCES

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-conversational-rag-reference#125]
### Describe the bug

the command 'pnpm run galileo-cli deploy --help' throws an error messages:

Deploy Galileo into your AWS account

USAGE
  $ galileo-cli deploy [--projen] [--profile <value>] [--config <value>] [--skipConfirmations] [--cdkCommand <value>] [--cdkRequireApproval <value>] [--build] [--saveExec]
    [--dryRun] [--replay]

FLAGS
  --[no-]build                  Perform build
  --cdkCommand=<value>          [default: deploy] CDK command to run
  --cdkRequireApproval=<value>  [default: never] CDK approval level
  --config=<value>              The config.json file to load/store configurations
  --dryRun                      Only log commands but don't execute them
  --profile=<value>             The profile set up for your AWS CLI (associated with your AWS account)
  --[no-]projen                 Run projen to synth project
  --replay                      Replay last successful task(s) execution
  --saveExec                    Save successful task(s) execution to enable replay
  --skipConfirmations           Skip prompt confirmations (always yes)

DESCRIPTION
  Deploy Galileo into your AWS account

EXAMPLES
  $ galileo-cli deploy --profile=myProfile --appRegion=ap-southeast-1 --llmRegion=us-west-2 --build --saveExec --skipConfirmations

  $ galileo-cli deploy --dryRun

  $ galileo-cli deploy --replay --skipConfirmations

(node:6235) [EACCES] Error: spawn galileo-cli EACCES

### Expected Behavior

no such error message

### Current Behavior

the command 'pnpm run galileo-cli deploy --help' throws an error messages:

Deploy Galileo into your AWS account

USAGE
  $ galileo-cli deploy [--projen] [--profile <value>] [--config <value>] [--skipConfirmations] [--cdkCommand <value>] [--cdkRequireApproval <value>] [--build] [--saveExec]
    [--dryRun] [--replay]

FLAGS
  --[no-]build                  Perform build
  --cdkCommand=<value>          [default: deploy] CDK command to run
  --cdkRequireApproval=<value>  [default: never] CDK approval level
  --config=<value>              The config.json file to load/store configurations
  --dryRun                      Only log commands but don't execute them
  --profile=<value>             The profile set up for your AWS CLI (associated with your AWS account)
  --[no-]projen                 Run projen to synth project
  --replay                      Replay last successful task(s) execution
  --saveExec                    Save successful task(s) execution to enable replay
  --skipConfirmations           Skip prompt confirmations (always yes)

DESCRIPTION
  Deploy Galileo into your AWS account

EXAMPLES
  $ galileo-cli deploy --profile=myProfile --appRegion=ap-southeast-1 --llmRegion=us-west-2 --build --saveExec --skipConfirmations

  $ galileo-cli deploy --dryRun

  $ galileo-cli deploy --replay --skipConfirmations

(node:6235) [EACCES] Error: spawn galileo-cli EACCES

### Reproduction Steps

just run the command 'pnpm run galileo-cli deploy --help'

### Environment details (OS name and version, etc.)

pnpm run prerequisite-check  > monorepo@0.0.0 prerequisite-check /home/ubuntu/environment/aws-genai-conversational-rag-reference > ./prerequisite-check.sh  Galileo Prerequisite Check...  system: Linux 6.5.0-1017-aws #17~22.04.2-Ubuntu SMP Mon Mar 25 20:28:54 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux pnpm: 9.0.5  node: v20.12.2  python: Python 3.11.0rc1  poetry: Poetry (version 1.8.2)  docker: Docker version 26.0.1, build d260a54  java: openjdk 18.0.2 2022-07-19 OpenJDK Runtime Environment Corretto-18.0.2.9.1 (build 18.0.2+9-FR) OpenJDK 64-Bit Server VM Corretto-18.0.2.9.1 (build 18.0.2+9-FR, mixed mode, sharing)  aws: aws-cli/2.15.38 Python/3.11.8 Linux/6.5.0-1017-aws exe/x86_64.ubuntu.22 prompt/off   Prerequisite check passed

**Comment by martenpayne** [comment]
Known spurious message - see note on https://aws-samples.github.io/aws-genai-conversational-rag-reference/getting-started/deploying-galileo.html
