### ISSUE TITLE
deployment failed

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-conversational-rag-reference#127]
### Describe the bug

Task "build" failed when executing "pnpm exec nx run-many --target=build --output-style=stream --nx-bail" (cwd: /home/ubuntu/environment/aws-genai-conversational-rag-reference)
 ELIFECYCLE  Command failed with exit code 1.

### Expected Behavior

no failure for deployment

### Current Behavior

Task "build" failed when executing "pnpm exec nx run-many --target=build --output-style=stream --nx-bail" (cwd: /home/ubuntu/environment/aws-genai-conversational-rag-reference)
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction Steps

git clone https://github.com/aws-samples/aws-genai-conversational-rag-reference
cd aws-genai-conversational-rag-reference

./scripts/resize.sh 300

wget -q -O - https://apt.corretto.aws/corretto.key | sudo gpg --dearmor -o /usr/share/keyrings/corretto-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main" | sudo tee /etc/apt/sources.list.d/corretto.list
sudo apt -qq update
sudo apt -qq install -y java-18-amazon-corretto-jdk

nvm install lts/iron
nvm use lts/iron
npm i -g pnpm

sudo apt -qq install -y python3.11
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 110
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 100
sudo update-alternatives --set python3 /usr/bin/python3.11
curl -sSL https://install.python-poetry.org | python3 -

pnpm install
pnpm build

### Environment details (OS name and version, etc.)

$ pnpm run prerequisite-check  > monorepo@0.0.0 prerequisite-check /home/ubuntu/environment/aws-genai-conversational-rag-reference > ./prerequisite-check.sh  Galileo Prerequisite Check...  system: Linux 6.5.0-1018-aws #18~22.04.1-Ubuntu SMP Fri Apr  5 17:44:33 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux pnpm: 9.0.6  node: v20.12.2  python: Python 3.11.0rc1  poetry: Poetry (version 1.8.2)  docker: Docker version 26.1.0, build 9714adc  java: openjdk 18.0.2 2022-07-19 OpenJDK Runtime Environment Corretto-18.0.2.9.1 (build 18.0.2+9-FR) OpenJDK 64-Bit Server VM Corretto-18.0.2.9.1 (build 18.0.2+9-FR, mixed mode, sharing)  aws: aws-cli/2.15.40 Python/3.11.8 Linux/6.5.0-1018-aws exe/x86_64.ubuntu.22 prompt/off   Prerequisite check passed

**Comment by martenpayne** [comment]
thanks for reporting this, we will investigate the issue shortly

**Comment by martenpayne** [comment]
Could you check the updated instructions & prerequisite package version (ensuring pnpm is >= 8 & < 9) and retest?

**Comment by martenpayne** [comment]
After fixing prerequisite package version instructions & code updates, "pnpm build" now completes successfully in the given environment.
