### ISSUE TITLE
[BUG] post-compile » docgen | jsii-docgen -o API.md fails due to missing dependencies

### ISSUE THREAD

**Issue by sociengineer** [aws-samples/aws-genai-conversational-rag-reference#75]
### Describe the bug

build fails at 'post-compile » docgen | jsii-docgen -o API.md' due to missing dependencies. such as zod-to-json-schema, zod, yaml and so on.

@aws/galileo-cdk: 👾 build » compile | jsii --silence-warnings=reserved-word
@aws/galileo-cdk: 👾 build » post-compile » docgen | jsii-docgen -o API.md
@aws/galileo-cdk: [Error: ENOENT: no such file or directory, stat '/Users/wookjae/Engineer/Prototyping/13.Amore-GenAI/aws-genai-conversational-rag-reference/packages/galileo-cdk/node_modules/xtend'] {
@aws/galileo-cdk:   errno: -2,
@aws/galileo-cdk:   code: 'ENOENT',
@aws/galileo-cdk:   syscall: 'stat',
@aws/galileo-cdk:   path: '/Users/wookjae/Engineer/Prototyping/13.Amore-GenAI/aws-genai-conversational-rag-reference/packages/galileo-cdk/node_modules/xtend'
@aws/galileo-cdk: }
@aws/galileo-cdk: 👾 Task "build » post-compile » docgen" failed when executing "jsii-docgen -o API.md" (cwd: /Users/wookjae/Engineer/Prototyping/13.Amore-GenAI/aws-genai-conversational-rag-reference/packages/galileo-cdk)
@aws/galileo-cdk: Warning: run-commands command "pnpm exec projen build" exited with non-zero status code

 ———————————————————————————————————————————————————————————————>
NX   Running target build for 17 projects failed

   Tasks not run because their dependencies failed or --nx-bail=true:
   
   - infra:build
   
   Failed tasks:
   
   - @aws/galileo-cdk:build

👾 Task "build" failed when executing "pnpm exec nx run-many --target=build --output-style=stream --nx-bail" (cwd: /Users/wookjae/Engineer/Prototyping/13.Amore-GenAI/aws-genai-conversational-rag-reference)

### Expected Behavior

No fails in pnpm build.

### Current Behavior

👾 Task "build" failed when executing "pnpm exec nx run-many --target=build --output-style=stream --nx-bail" (cwd: /Users/wookjae/Engineer/Prototyping/13.Amore-GenAI/aws-genai-conversational-rag-reference)

### Reproduction Steps

git pull the latest version of mainline
pnpm i
pnpm projen
pnpm build

### Environment details (OS name and version, etc.)

pnpm: 8.9.2  node: v18.18.0  python: Python 3.11.5  poetry: Poetry (version 1.6.1)  docker: Docker version 24.0.6, build ed223bc  java: openjdk 17.0.8.1 2023-08-22 LTS OpenJDK Runtime Environment Corretto-17.0.8.8.1 (build 17.0.8.1+8-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.8.8.1 (build 17.0.8.1+8-LTS, mixed mode, sharing)  aws: aws-cli/2.13.31 Python/3.11.6 Darwin/22.6.0 exe/x86_64 prompt/off

**Comment by sperka** [comment]
@sociengineer has the above recommendation solved your issue?
